### ISSUE TITLE
Missing reference to business-finance icons pack in style.css file

### ISSUE THREAD

**Issue by Pe5h4** [Vectopus/Atlas-icons-font#10]
**Confirm uniqueness of the issue**
I have searched the [issues](https://github.com/Vectopus/Atlas-icons-font/issues) of this repository and believe that this is not a duplicate.

**Describe the bug**

In mian `style.css` file, there is a reference to a non-existent path to `/business-finance/style.css` icons , thus all the app icons are not loaded and the application cant be build.

https://github.com/Vectopus/Atlas-icons-font/blob/main/style.css#L5

```
@import "packs/basic-ui/style.css";
@import "packs/business-finance/style.css"; // Non-existent reference
@import "packs/christmas/style.css";
```

**Steps to Reproduce**
  1. Install the atlas icons package `npm i @vectopus/atlas-icons`
  2. Import icons `@import url("/node_modules/@vectopus/atlas-icons/style.css")`
  3. See error in console
  ```
  ERROR in ./node_modules/@vectopus/atlas-icons/style.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/@vectopus/atlas-icons/style.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve 'packs/business-finance/style.css'
  ```

**Expected behavior**
No reference error

**Possible solution**
Remove the reference or correct the path

**Bypass for atlas-icons users**
Until fixed, import only the icons you need separately from `packs` dir

```
@import url("/node_modules/@vectopus/atlas-icons/packs/achievement/style.css");
@import url("/node_modules/@vectopus/atlas-icons/packs/arrow/style.css");
@import url("/node_modules/@vectopus/atlas-icons/packs/audio/style.css");
...
```

**Comment by mosamy19** [comment]
Hi @Pe5h4!
Thank you for reporting this issue and sorry for inconvenience.
I just fixed this issue, please update your dependencies.

Thank you

**Comment by Pe5h4** [comment]
Hello @mosamy19,

thank you for prompt fix & response!
