### ISSUE TITLE
Support react native vector icon

### ISSUE THREAD

**Issue by bhyoo99** [Vectopus/Atlas-icons-font#3]
First of all, thank you so much for making these incredible icons.

I want to use your resource for my react native project, 
but I can't find the merged TTF file.

or I think it's a good idea to update here
https://github.com/oblador/react-native-vector-icons

**Comment by mosamy19** [comment]
Hi @bhyoo99! Thank you for your interest in Atlas Icons.
Unfortunately this won't be possible at the moment.
But we added a new SVG icon package for React Native https://github.com/Vectopus/Atlas-icons-react-native
