### ISSUE TITLE
Icons from the medical pack display incorrect icon

### ISSUE THREAD

**Issue by matteobarbera** [Vectopus/Atlas-icons-font#9]
Hi! Thanks for creating this extensive icon pack.

While testing different icons I discovered that icons from the medical pack display an incorrect icon.

```html
<head>
  <link rel="stylesheet" href="https://unpkg.com/@vectopus/atlas-icons/style.css">
</head>
<body>
  <i class="at-air-conditioner"></i>
  <i class="at-bacteria"></i>
  <i class="at-lightbulb-idea-person"></i>
  <i class="at-angel-heart"></i>
  <i class="at-user-target"></i>
  <i class="at-abacus"></i>
  <i class="at-asian-pagoda"></i>
  <!-- Icons from the medical pack display wrong icon -->
  <i class="at-ear"></i> 
  <i class="at-ambulance"></i>
</body>
```
Codepen with the above code: https://codepen.io/i_could_be/pen/ExdNyNp

**Comment by mosamy19** [comment]
Hi @matteobarbera!
Thank you for reporting this issue and sorry for inconvenience.
I just fixed this issue, please update your dependencies.

Thank you
